// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsX0RUdP0ZjCUFx8PWNelbDZbnynM4mWM',
    appId: '1:37708309111:web:c0c96f309a49c9c3539c72',
    messagingSenderId: '37708309111',
    projectId: 'matrimoney-aefe9',
    authDomain: 'matrimoney-aefe9.firebaseapp.com',
    storageBucket: 'matrimoney-aefe9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqdDgVQqiuCMgXr8p7lqFGjeQamKsVAY',
    appId: '1:37708309111:android:e2b145875828f040539c72',
    messagingSenderId: '37708309111',
    projectId: 'matrimoney-aefe9',
    storageBucket: 'matrimoney-aefe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0TmVliisRk0ZqgzUImEhkXYpQWJrpyCg',
    appId: '1:37708309111:ios:d2ba684821549aa3539c72',
    messagingSenderId: '37708309111',
    projectId: 'matrimoney-aefe9',
    storageBucket: 'matrimoney-aefe9.appspot.com',
    iosClientId: '37708309111-30u9jcnjqt31u26e1rg2pu50gg69tbdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppOneOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0TmVliisRk0ZqgzUImEhkXYpQWJrpyCg',
    appId: '1:37708309111:ios:d2ba684821549aa3539c72',
    messagingSenderId: '37708309111',
    projectId: 'matrimoney-aefe9',
    storageBucket: 'matrimoney-aefe9.appspot.com',
    iosClientId: '37708309111-30u9jcnjqt31u26e1rg2pu50gg69tbdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppOneOne',
  );
}
